# Generated by Django 4.2 on 2023-05-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqli_easy', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='chall',
        ),
    ]
