# Generated by Django 4.2 on 2023-05-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqli_easy', '0003_rename_users_chall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chall',
            new_name='Users',
        ),
    ]
